"""The words on a dashboard, in the station's language.

**One setting, `language`, reaches everything** -- the chart labels, the moon
phases, the compass, every translated skin. A Grafana dashboard is read by
the same people, so it is not the place to make an exception. A German
station gets "Außentemperatur" on the axis and "Vergleich" in the tab.

Most of a dashboard needs no words of its own. A panel showing `outTemp` is
titled by `units.obs_label(obs, language)`, which every other renderer here
already uses -- so the hundred charts out of `plots.toml` are translated
without a single entry below. What is left is the scaffolding: the four
dashboard names, the two variable labels, and a handful of words like "today"
that hold a title together.

**The English lives here, not in a file.** Same rule as `language.py` itself:
a fallback that can be missing is not a fallback. A language that translates
twelve of these twenty shows twelve translated and eight in English, which is
a page somebody can still use.

To translate them, add a `[dashboard]` section to `lang/<code>.toml` with
these keys. Anything absent stays English.
"""

from __future__ import annotations

from typing import Any

#: Every word this package writes that is not a reading's own name. The keys
#: are what goes in `lang/<code>.toml` under `[dashboard]`.
ENGLISH: dict[str, str] = {
    # The dashboards. Short, because they are read in a browser tab and in a
    # search box, both of which cut at about twenty characters.
    "weather": "Weather",
    "now": "Now",
    "one_location": "One location",
    "compare": "Compare",
    "operations": "Operations",
    "charts": "Charts",

    # The spans a chart set is grouped by.
    "day": "day",
    "week": "week",
    "month": "month",
    "year": "year",

    # The variables at the top of a dashboard.
    "location": "Location",
    "reading": "Reading",

    # The few titles that are not simply a reading's name.
    "today": "today",
    "last_seen": "Last reading",
    "indoors": "Indoors, batteries and signal",
    "every_location": "every location",
    "sun": "Sun",

    # The little "i" beside a panel title. Worth translating: it is where
    # somebody looking at an unfamiliar station finds out what is measured.
    "about_compare": ("Every location on one axis. Pick the reading above; "
                      "the legend names the stations."),
    "about_last_seen": ("How long ago each location last wrote anything. An "
                        "archive interval is five minutes, so a quarter of "
                        "an hour is three missed ones."),
    "about_interval": ("Every average is weighted by this. A step here is "
                       "where an unweighted average would start disagreeing "
                       "with the station's own pages."),
    "about_battery": "Non-zero is what most consoles mean by 'replace me'.",
    "generated": ("Generated by `weewx-evo grafana provision` on {when}. "
                  "Edits here are overwritten on the next run; change the "
                  "charts in `plots.toml` or on the settings page."),
}


class Words:
    """The dashboard vocabulary for one language.

    A mapping rather than a function so a caller reads `w.now` instead of
    `w("now")` -- these appear four deep inside dictionary literals, and the
    quotes add up.
    """

    __slots__ = ("_said", "language")

    def __init__(self, language: Any = None) -> None:
        self.language = language
        self._said: dict[str, str] = {}
        for key, english in ENGLISH.items():
            self._said[key] = (
                language.text("dashboard", key, english) if language is not None
                else english)

    def __getattr__(self, key: str) -> str:
        try:
            return self._said[key]
        except KeyError:
            # Not answered blindly. A typo here would otherwise become an
            # empty panel title, and an empty title reads as a Grafana fault
            # rather than ours -- the same reason `Tags` refuses a name it
            # does not know instead of politely returning something.
            raise AttributeError(
                f"no dashboard word called {key!r}; add it to "
                f"grafana/words.ENGLISH") from None

    def obs(self, obs_type: str) -> str:
        """A reading's name, translated. The commonest word on a dashboard."""
        from .. import units
        return units.obs_label(obs_type, self.language)

    def span(self, name: str) -> str:
        """A chart span, translated where this language has the word."""
        return self._said.get(name, name)

    def title(self, *parts: str) -> str:
        """A dashboard title: the product, then what this one answers."""
        return ": ".join([self.weather, *(p for p in parts if p)])
