"""The schema WeeWX seeds a new database with.

Generated from weewx/schemas/wview_extended.py (WeeWX 5.5.0). It is only
ever used to create a database that does not exist yet. Once a database is
there, its schema comes from the file -- see db/schema.py.
"""

from __future__ import annotations

# (column, SQL type). Order matters: it is the column order of the table.
ARCHIVE_TABLE: tuple[tuple[str, str], ...] = (
    ('dateTime', 'INTEGER NOT NULL PRIMARY KEY'),
    ('usUnits', 'INTEGER NOT NULL'),
    ('interval', 'INTEGER NOT NULL'),
    ('altimeter', 'REAL'),
    ('appTemp', 'REAL'),
    ('appTemp1', 'REAL'),
    ('barometer', 'REAL'),
    ('batteryStatus1', 'REAL'),
    ('batteryStatus2', 'REAL'),
    ('batteryStatus3', 'REAL'),
    ('batteryStatus4', 'REAL'),
    ('batteryStatus5', 'REAL'),
    ('batteryStatus6', 'REAL'),
    ('batteryStatus7', 'REAL'),
    ('batteryStatus8', 'REAL'),
    ('cloudbase', 'REAL'),
    ('co', 'REAL'),
    ('co2', 'REAL'),
    ('consBatteryVoltage', 'REAL'),
    ('dewpoint', 'REAL'),
    ('dewpoint1', 'REAL'),
    ('ET', 'REAL'),
    ('extraHumid1', 'REAL'),
    ('extraHumid2', 'REAL'),
    ('extraHumid3', 'REAL'),
    ('extraHumid4', 'REAL'),
    ('extraHumid5', 'REAL'),
    ('extraHumid6', 'REAL'),
    ('extraHumid7', 'REAL'),
    ('extraHumid8', 'REAL'),
    ('extraTemp1', 'REAL'),
    ('extraTemp2', 'REAL'),
    ('extraTemp3', 'REAL'),
    ('extraTemp4', 'REAL'),
    ('extraTemp5', 'REAL'),
    ('extraTemp6', 'REAL'),
    ('extraTemp7', 'REAL'),
    ('extraTemp8', 'REAL'),
    ('forecast', 'REAL'),
    ('hail', 'REAL'),
    ('hailBatteryStatus', 'REAL'),
    ('hailRate', 'REAL'),
    ('heatindex', 'REAL'),
    ('heatindex1', 'REAL'),
    ('heatingTemp', 'REAL'),
    ('heatingVoltage', 'REAL'),
    ('humidex', 'REAL'),
    ('humidex1', 'REAL'),
    ('illuminance', 'REAL'),
    ('inDewpoint', 'REAL'),
    ('inHumidity', 'REAL'),
    ('inTemp', 'REAL'),
    ('inTempBatteryStatus', 'REAL'),
    ('leafTemp1', 'REAL'),
    ('leafTemp2', 'REAL'),
    ('leafWet1', 'REAL'),
    ('leafWet2', 'REAL'),
    ('lightning_distance', 'REAL'),
    ('lightning_disturber_count', 'REAL'),
    ('lightning_energy', 'REAL'),
    ('lightning_noise_count', 'REAL'),
    ('lightning_strike_count', 'REAL'),
    ('luminosity', 'REAL'),
    ('maxSolarRad', 'REAL'),
    ('nh3', 'REAL'),
    ('no2', 'REAL'),
    ('noise', 'REAL'),
    ('o3', 'REAL'),
    ('outHumidity', 'REAL'),
    ('outTemp', 'REAL'),
    ('outTempBatteryStatus', 'REAL'),
    ('pb', 'REAL'),
    ('pm10_0', 'REAL'),
    ('pm1_0', 'REAL'),
    ('pm2_5', 'REAL'),
    ('pressure', 'REAL'),
    ('radiation', 'REAL'),
    ('rain', 'REAL'),
    ('rainBatteryStatus', 'REAL'),
    ('rainRate', 'REAL'),
    ('referenceVoltage', 'REAL'),
    ('rxCheckPercent', 'REAL'),
    ('signal1', 'REAL'),
    ('signal2', 'REAL'),
    ('signal3', 'REAL'),
    ('signal4', 'REAL'),
    ('signal5', 'REAL'),
    ('signal6', 'REAL'),
    ('signal7', 'REAL'),
    ('signal8', 'REAL'),
    ('snow', 'REAL'),
    ('snowBatteryStatus', 'REAL'),
    ('snowDepth', 'REAL'),
    ('snowMoisture', 'REAL'),
    ('snowRate', 'REAL'),
    ('so2', 'REAL'),
    ('soilMoist1', 'REAL'),
    ('soilMoist2', 'REAL'),
    ('soilMoist3', 'REAL'),
    ('soilMoist4', 'REAL'),
    ('soilTemp1', 'REAL'),
    ('soilTemp2', 'REAL'),
    ('soilTemp3', 'REAL'),
    ('soilTemp4', 'REAL'),
    ('supplyVoltage', 'REAL'),
    ('txBatteryStatus', 'REAL'),
    ('UV', 'REAL'),
    ('uvBatteryStatus', 'REAL'),
    ('windBatteryStatus', 'REAL'),
    ('windchill', 'REAL'),
    ('windDir', 'REAL'),
    ('windGust', 'REAL'),
    ('windGustDir', 'REAL'),
    ('windrun', 'REAL'),
    ('windSpeed', 'REAL'),
)

# Every observation gets a daily summary table; wind additionally gets a
# vector one, which is where the mean direction comes from.
_NOT_OBSERVATIONS = frozenset({'dateTime', 'usUnits', 'interval'})

DAY_SUMMARIES: tuple[tuple[str, str], ...] = (
    *tuple((name, 'scalar') for name, _ in ARCHIVE_TABLE
           if name not in _NOT_OBSERVATIONS),
    ('wind', 'vector'),
)
